config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'resque/server'
  ActiveAdmin.routes(self)
  # devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions',
                                              confirmations: 'users/confirmations' }
  resources :categories,    except: %i[new]
  resources :images,        except: %i[new edit update destroy]
  resources :comments,      only: %i[create]
  resources :likes,         only: %i[create destroy]
  resources :subscriptions, only: %i[create destroy]
  resource  :locales,       only: %i[update]
  root 'welcome#index'
  mount Resque::Server.new, at: '/resque' unless Rails.env.production?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

# category model
class Category < ApplicationRecord
  validates_presence_of :owner_id, :name
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user, foreign_key: 'owner_id'
  has_many :images, dependent: :destroy
  has_many :subscriptions, dependent: :delete_all
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# category controller class
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy edit update]
  before_action :sort_category, only: %i[index show]

  def index; end

  def show
    @category = Category.friendly.find(params[:id])
    @subscription_exist = user_signed_in? ? @category.subscriptions.find_by(user_id: current_user.id).present? : false
  end

  def create
    if current_user.categories.create!(category_params)
      redirect_to categories_path
    else
      redirect_to new_category_path
    end
  end

  def destroy
    begin
      current_user.categories.friendly.find(params[:id]).destroy
    rescue ActiveRecord::RecordNotFound
      redirect_to categories_path(error: 'no instance')
    rescue
      redirect_to categories_path(error: 'undefined error')
    end
    redirect_to categories_path
  end

  def edit; end

  def update
    return unless current_user.categories.friendly.find(params[:id]).update(name: params[:name])

    redirect_to categories_path
  end

  private

  def category_params
    params.permit( :name)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# categories helper
module CategoriesHelper
  def find_popular_image(category)
    category.images.sort_by(&:likes_count).last
  end

  def button_for_subscribe
    link_to t('site.category.subscribe'), subscriptions_path, method: :post, remote: true, 'data-turbolinks': 'false',
            class: 'btn btn-secondary d-table-cell', id: 'category-subscribe'
  end

  def button_for_unsubscribe(category_id)
    link_to t('site.category.unsubscribe'), subscription_path(category_id), method: :delete, remote: true, 'data-turbolinks': 'false',
            class: 'btn btn-secondary d-table-cell', id: 'category-unsubscribe'
  end
end

app/views/categories/_menu.html.haml
-#!!!
%style
  =raw Gallery::Application.assets.find_asset('application.css').source
%ul.menu
  %li
    %a(href='/') Главная
  %li
    %a(href='categories') Категории
  %li
    %a(href='') "Что то еще"
  %li
    %ul
      %li
        - if user_signed_in?
          = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          = link_to 'Sign In', 'users/sign_in'

app/views/categories/_new.html.haml
.form-group.container.mt-2
  = form_with model: @category, local: true do |f|
    = f.label t(:'site.category.name')
    = f.text_field :name, id: 'category-name_field'
    = f.submit t(:'site.common.create'), class: 'btn btn-primary', id: 'category-create_button'

app/views/categories/edit.html.haml
= form_with model: @category, url: category_path, method: :patch, local: true do |f|
  = f.label :category
  = f.text_field :name
  = f.submit :submit

app/views/categories/index.html.haml
.col-12
  %h3.text-center= t(:'site.category.list')
.col-12.col-lg-9.text-center
  = link_to t(:'site.category.create'), '#createCategory', class: 'btn btn-primary', id: 'category-create_collapse',
            'data-toggle': 'collapse', role: 'button'
  #createCategory.collapse
    = render 'new.html.haml'
  -#.row
  -#.mt-5.col
  .card-columns.mt-5
    - @categories_with_rating.each do |hash|
      - img = find_popular_image(hash.fetch(:category))
      .card.text-center.w-auto.mx-auto{style: 'background: linear-gradient(45deg, lightyellow, lightgray);'}
        - if img.present?
          = link_to image_tag("#{img.path.thumb}", alt: img[:path],
                              class: 'text-center img-adjusted'),
                    category_path(hash.fetch(:category)), class: 'card-image-top m-2'
        - else
          = link_to(category_path(hash.fetch(:category)), class: 'text-decoration-none') do
            .rectangle.d-table-cell.align-middle
              %p.text-white= t(:'site.category.empty')
        .card-body.card-text.m-10
          %h4.card-title.text-center.mb-0
            = hash.fetch(:category).name
            %br
            - if user_signed_in? && hash.fetch(:category).owner_id == current_user.id
              = link_to 'rename', edit_category_path(hash.fetch(:category)), class: 'card-link text-center card-text'
              = link_to 'delete', hash.fetch(:category), method: :delete, data: { confirm: t(:'site.common.sure') },
                         class: 'card-link card-text'
= render('share/sidebar')

app/views/categories/show.html.haml
.col-12.col-md-9.text-center
  .container.mb-5
    %h1.mr-5{style: 'display:inline'}= @category.name
    %span
      - if @subscription_exist
        = button_for_unsubscribe(@category.id)
      - else
        = button_for_subscribe
    %br
    = link_to t(:'site.image.add'), '#createCategory', class: 'btn btn-primary w-auto wt-3 mt-3',
      'data-toggle': 'collapse', role: 'button', id: 'image-button_collapse'
    #createCategory.collapse
      .form-group.container.mt-2
        = form_with model: @image, url: images_path, local: true do |f|
          = f.file_field :path, id: 'image-file_pick'
          = f.hidden_field :cat_id, value:  params[:id]
          = f.submit t(:'site.common.add'), class: 'btn btn-primary', id: 'image-add_button'
  - @category.images.each do |image|
    = link_to(image_tag(image.path.thumb.to_s, alt: image[:path], class: 'p-1'), image_path(image))
= render'share/sidebar'