config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'resque/server'
  ActiveAdmin.routes(self)
  # devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions',
                                              confirmations: 'users/confirmations' }
  resources :categories,    except: %i[new]
  resources :images,        except: %i[new edit update destroy]
  resources :comments,      only: %i[create]
  resources :likes,         only: %i[create destroy]
  resources :subscriptions, only: %i[create destroy]
  resource  :locales,       only: %i[update]
  root 'welcome#index'
  mount Resque::Server.new, at: '/resque' unless Rails.env.production?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
# frozen_string_literal: true

# image model
class Image < ApplicationRecord
  validates_presence_of :path
  validates_numericality_of :likes_count, greater_than_or_equal_to: 0
  validates_numericality_of :comments_count, greater_than_or_equal_to: 0
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :path, ImageUploader
  paginates_per 10
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :delete_all

  def to_s
    path.to_s
  end
  def name
    path.to_s.match %r{ \/[a-zA-Z0-_.\-]*\z }
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

# image controller class
require 'redis'
# Image Controller
class ImagesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :find_category,      only: %i[create]

  def show
    redis = Redis.new
    @image = Image.friendly.find(params[:id])

    @likes_count = redis.get("image:#{@image.id}:likes_count") || @image.likes.size
    @path_to_img = ActionController::Base.helpers.path_to_image('liked.svg')
    @like_exist = user_signed_in? ? Image.friendly.find(params['id']).likes.where(user_id: current_user.id).exists? : false
  end

  def index
    @images = Image.all.order(likes_count: :desc).page(params[:page]).per(12)
  end

  def create
    @category.images.create(image_params) unless image_params.empty?
    Resque.enqueue(EmailJob, @category.id)
    redirect_to @category
  end

  private

  def image_params
    params.permit(:path)
  end

  def find_category
    @category = Category.friendly.find(params[:cat_id]) if params[:cat_id]
  end
end

app/views/images/index.html.haml
.col-12.col-lg-9
  = Rails.logger.fatal 'ImagesView#index, @categories_with_rating is present' if Rails.logger.level == 4 && @categories_with_rating.present?
  %h3.text-center= t(:'site.image.list')
  .row
    - @images.each do |img|
      .qwe{style: 'flex-grow: auto;'}
        = link_to image_tag( "#{img.path.thumb}", alt: img[:path], style: ' object-fit: fill;' ),
                  image_path(img), style: ''
  .container.d-flex.justify-content-center
    = paginate @images, theme: 'twitter-bootstrap-4'
= render 'share/sidebar'

app/views/images/show.html.haml
.col-12.col-sm-9.mt-5
  = Rails.logger.fatal 'ImagesView#show, @categories_with_rating is present' if Rails.logger.level == 4 && @categories_with_rating.present?
  = image_tag "#{@image.path}", alt: @image[:path], class: 'w-100',
              'data-target': '#imageFullScreen', 'data-toggle': 'modal', type: 'button'
  #imageFullScreen.modal.fade{role: 'dialog', tabindex: '-1'}
    .modal-dialog.modal-dialog-centered.text-center.modal-lg{role: 'document'}
      .modal-content.w-auto
        .modal-body
          = image_tag "#{@image.path}", alt: @image[:path], 'data-dismiss': 'modal', class: 'img-fluid'

%div.container-fluid.col-12.col-sm-3.mt-5{'data-turbolinks': 'false'}
  %p.menu.pt-5.text-center
    - if @like_exist
      = link_for_unlike(@image)
    - else
      = link_for_like
    %span#likesCount
      = @likes_count
      = @likes_count == 1 ? t(:'site.image.like') : t(:'site.image.likes')

  - if @image.comments.size == 0
    %p= t(:'site.image.comment')
  - else
    - @image.comments.each do |comment|
      .row
        .col-2
          = image_tag comment.user.avatar.to_s, alt: 'avatar', width: 30
        .col-10.d-inline-block
          = comment.created_at.strftime "%F %R"
          %p= comment&.body
  %p.menu.pt-5
    = form_with model: @comment, url: comments_path, local: true do |f|
      = f.label t(:'site.image.new_comment'), class: 'text-center'
      = f.text_area_tag :body
      = f.hidden_field :image_id, value: @image.id
      = f.submit t(:'site.common.create')