config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'resque/server'
  ActiveAdmin.routes(self)
  # devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions',
                                              confirmations: 'users/confirmations' }
  resources :categories,    except: %i[new]
  resources :images,        except: %i[new edit update destroy]
  resources :comments,      only: %i[create]
  resources :likes,         only: %i[create destroy]
  resources :subscriptions, only: %i[create destroy]
  resource  :locales,       only: %i[update]
  root 'welcome#index'
  mount Resque::Server.new, at: '/resque' unless Rails.env.production?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Gallery
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -# Header
    = Rails.logger.fatal 'layouts/application' if Rails.logger.level == 4
    = Rails.logger.fatal 'layouts/application, @categories_with_rating is present' if Rails.logger.level == 4 && @categories_with_rating.present?
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-secondary
      .navbar-collapse.order-0.text-center
        .navbar-brand= t(:'site.menu.title')
        %ul.navbar-nav.ml-auto
          %li.active.nav-item
            %a.nav-link(href=root_path id='menu-main')= t(:'site.menu.main')
          %li.nav-item
            %a.nav-link.pr-0(href=categories_path id='menu-categories')= t(:'site.menu.categories')

          %li.nav-item.dropdown.pr-2
            %a.nav-link.dropdown-toggle.text-center(href='#' role='button' data-toggle='dropdown' id='menu-category_list_main')
            .dropdown-menu.bg-secondary.text-center
              - find_categories_rating.first(5).each_with_index do |category, index|
                = link_to category[:category].name, category_path(category[:category]),
                          class: 'dropdown-item bg-secondary text-white', id: "menu-category_list_#{index}"
          %li.nav-item
            %a.nav-link.pl-0(href=images_path id='menu-images')= t(:'site.menu.images')
          %li.nav-item
            %a.nav-link(href=admin_root_path)= t(:'site.menu.admin')

      .navbar-collapse.order-1
        %ul.navbar-nav.ml-auto
          %li.nav-item.dropdown.pr-3
            = link_to image_tag("#{find_locale}.png", alt: params[:locale], width: 40), '#', id: 'menu-locale_main',
                      role: 'button', 'data-toggle': 'dropdown', class: 'nav-link dropdown-toggle text-center'
            .dropdown-menu.bg-secondary.w-auto
              - %w[en ru].each_with_index do |lang, index|
                - unless find_locale == lang
                  = link_to image_tag(lang + '.png', alt: lang, width: 40), locales_path(locale: lang), method: :put,
                            controller: :locales, action: :update, id: "menu-locale_#{index}",
                            class: 'dropdown-item bg-secondary text-white text-center'
          - if user_signed_in?
            %li.nav-item.dropdown.pr-3
              = link_to image_tag(avatar_to_display, alt: 'profile', width: 30), '#', id: 'menu-profile_main',
                        role: 'button', 'data-toggle': 'dropdown', class: 'nav-link dropdown-toggle text-center'
              .dropdown-menu.bg-secondary.w-auto
                = link_to t(:'views.register.profile'), edit_user_registration_path, id: 'menu-profile_profile',
                          class: 'nav-link text-center bg-secondary dropdown-item'
                = link_to t(:'site.common.sign_out'), destroy_user_session_path, method: :delete, id: 'menu-profile-sign_out',
                          class: 'nav-link text-center bg-secondary dropdown-item'
          %li.nav-item
            - if user_signed_in?
              = link_to t(:'site.common.sign_out'), destroy_user_session_path, method: :delete, id: 'menu-sign_out',
                        class: 'nav-link text-center text-uppercase'
            - else
              = link_to t(:'site.common.sign_in'), new_user_session_path, class: 'nav-link text-center', id: 'menu-sign_in'
    - if notice.present? || alert.present?
      %p.notice.text-center= notice
      %p.alert.text-center= alert
    -# end of header

    .container-fluid
      .row
        = yield

    -# footer
    %footer.page-footer.font-small.bg-color.red
      .container.text-center
        .row
          .col-md-12.mt-5
            = link_to image_tag('facebook.svg', width: 40), 'www.facebook.com'
            = link_to image_tag('twitter.svg', width: 40), 'www.twitter.com'
            = link_to image_tag('instagram.svg', width: 40), 'www.instagram.com'
            = link_to image_tag('vk.svg', width: 40), 'www.vk.ru'
        .footer-copyright
          %span © 2019 Copyright:
          %a{href: 'https://powerful-peak-65522.herokuapp.com'} https://powerful-peak-65522.herokuapp.com

    -# end of footer